# Generated by Django 5.0.3 on 2024-03-26 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='to_review',
        ),
        migrations.RemoveField(
            model_name='like',
            name='to_review',
        ),
        migrations.AddField(
            model_name='comment',
            name='to_log',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.log'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='to_log',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.log'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
