# Generated by Django 5.0.3 on 2024-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_comment_to_review_remove_like_to_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='first_time',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='progress',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
