# Generated by Django 5.0.3 on 2024-03-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_log_first_time_log_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='progress',
        ),
        migrations.AddField(
            model_name='log',
            name='completed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
