# Generated by Django 5.0.3 on 2024-03-27 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_log_progress_log_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
