# Generated by Django 5.0.3 on 2024-03-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_log_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='platform',
        ),
        migrations.AddField(
            model_name='log',
            name='platform_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
