# Generated by Django 4.2.11 on 2024-04-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_log_platform_log_platform_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-date_posted']},
        ),
    ]
