# Generated by Django 4.2.11 on 2024-04-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_commentlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='to_log',
            new_name='to_comment',
        ),
    ]
