# Generated by Django 5.0.3 on 2024-03-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('genres', models.JSONField()),
                ('platforms', models.JSONField()),
                ('cover', models.CharField(max_length=15)),
            ],
        ),
    ]
