# Generated by Django 5.0.3 on 2024-03-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
