# Generated by Django 5.0.3 on 2024-03-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_cover_remove_game_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
    ]
