# Generated by Django 5.0.3 on 2024-03-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.CharField(),
        ),
    ]
