# Generated by Django 5.0.3 on 2024-03-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_id',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
