# Generated by Django 5.0.3 on 2024-03-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
