# Generated by Django 4.2.11 on 2024-04-04 11:51

import chronicled.profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[chronicled.profiles.validators.validate_no_spaces, django.core.validators.MinLengthValidator(5)]),
        ),
    ]
