# Generated by Django 4.2.11 on 2024-04-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
